added more tests

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -37,7 +37,7 @@ jobs:
       run: |
         cd dist
         sha256sum -c ./*.sha256
-        if [[ $? -ne 0 ]]; then "Checkum check failed."; exit 1; fi
+        [[ $? -ne 0 ]] && echo "Checksum check failes." && exit 1
       shell: bash
     
     - name: Run sha256 checksum (fail on purpose)
@@ -45,7 +45,7 @@ jobs:
         cd dist
         echo "a" >> arm_Image.sha256
         sha256sum -c ./*.sha256
-        if [[ $? -ne 0 ]]; then "Checkum check failed. Not exiting to test."; fi
+        [[ $? -ne 0 ]] && echo "Checksum check failes. Not exiting to test."
       shell: bash
     
     - name: Save distribution files
@@ -69,7 +69,7 @@ jobs:
       run: |
         cd distribution-files
         sha256sum -c ./*.sha256
-        if [[ $? -ne 0 ]]; then "Checkum check failed."; exit 1; fi
+        [[ $? -ne 0 ]] && echo "Checksum check failes. Will fail because of the changes in the last job."
       shell: bash
     
     - name: Run sha256 checksum (fail on purpose)
@@ -77,7 +77,7 @@ jobs:
         cd distribution-files
         echo "a" >> arm_Image.sha256
         sha256sum -c ./*.sha256
-        if [[ $? -ne 0 ]]; then "Checkum check failed."; exit 1; fi
+        [[ $? -ne 0 ]] && echo "Checksum check failes." && exit 1
       shell: bash
       
     - name: Create release
