testing actions faster

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -2,90 +2,67 @@ name: Test Creating Release
 
 on:
   workflow_dispatch:
+
     inputs:
       release_name:
         type: string
         description: 'Release Name'
         required: true
-      relese_description:
-        type: string
-        description: 'Release Description'
-        required: false
       tag_name:
         type: string
         description: 'Tag Name'
         required: true
-        
-  
+      is_prerelease:
+        type: boolean
+        default: false
+        description: 'Pre-release?'
+        required: true
+      linux_kernel_version:
+        type: string
+        description: 'Linux kernel version'
+        required: true
+      buildroot_version:
+        type: string
+        description: 'Buildroot version'
+        required: true
+      extra_description:
+        type: string
+        description: "Description"
+        required: false
+
+
 jobs:
 
-  build_kernel_arm64:
+  testing_sha256:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
-
-    - name: Install dependencies
-      run: sudo apt update && sudo apt install meld build-essential libncurses5-dev bison flex gcc-aarch64-linux-gnu libelf-dev -y
-
-    - name: Build arm64 kernel
-      run: ./build.sh -nka arm64
+    - name: Create text file
+      run: echo "testing" > test.txt
       shell: bash
     
-    - name: Run sha256 checksum
+    - name: Create sha256 from text file
+      run: sha256sum test.txt > test.sha256
+      shell: bash
+    
+    - name: Check sha256
       run: |
-        cd dist
-        sha256sum -c ./*.sha256
-        [[ $? -ne 0 ]] && echo "Checksum check failes." && exit 1
+        sha256sum -c test.sha256
+        if [[ $? -ne 0 ]]; then
+          echo "Checksum failed."
+          exit 1
+        fi 
       shell: bash
     
-    - name: Run sha256 checksum (fail on purpose)
+    - name: Make failure
+      run: echo "aa" >> test.sha256
+      shell: bash
+    
+    - name: Check sha256 (should fail)
       run: |
-        cd dist
-        echo "a" >> arm_Image.sha256
-        sha256sum -c ./*.sha256
-        [[ $? -ne 0 ]] && echo "Checksum check failes. Not exiting to test."
+        sha256sum -c test.sha256
+        if [[ $? -ne 0 ]]; then
+          echo "Checksum failed."
+          exit 1
+        fi 
       shell: bash
-    
-    - name: Save distribution files
-      uses: actions/upload-artifact@v3
-      with:
-        name: distribution-files
-        path: dist
-        retention-days: 1
-  
-  release:
-    needs: build_kernel_arm64
-    
-    runs-on: ubuntu-latest
-    
-    steps:
-
-    - name: Download distribution files
-      uses: actions/download-artifact@v3
-    
-    - name: Run sha256 checksum
-      run: |
-        cd distribution-files
-        sha256sum -c ./*.sha256
-        [[ $? -ne 0 ]] && echo "Checksum check failes. Will fail because of the changes in the last job."
-      shell: bash
-    
-    - name: Run sha256 checksum (fail on purpose)
-      run: |
-        cd distribution-files
-        echo "a" >> arm_Image.sha256
-        sha256sum -c ./*.sha256
-        [[ $? -ne 0 ]] && echo "Checksum check failes." && exit 1
-      shell: bash
-      
-    - name: Create release
-      uses: softprops/action-gh-release@v1
-      with:
-        name: ${{ github.event.inputs.release_name }}
-        body: ${{ github.event.inputs.relese_description }}
-        tag_name: ${{ github.event.inputs.tag_name }}
-        files: |
-          ./distribution-files/arm_Image
-          ./distribution-files/arm_Image.sha256
